name: sellermultivendor
description: A new Flutter project.

publish_to: "none"
version: 2.9.2+18

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  http: ^1.2.0
  shared_preferences: ^2.0.11
  connectivity_plus: ^5.0.2
  firebase_auth: ^5.0.0
  cached_network_image: ^3.3.1 
  firebase_core: ^3.0.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.7
  sms_autofill: ^2.3.1
  image_picker: ^1.0.1
  fl_chart: ^0.68.0
  file_picker: ^8.0.3
  sticky_headers: ^0.3.0+2
  html_editor_enhanced: ^2.5.1
  mime: ^1.0.3
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.15.0
  flutter_widget_from_html: ^0.15.0
  provider: ^6.0.5
  google_maps_flutter: ^2.2.2
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  flutter_email_sender: ^6.0.1
  bloc: ^8.1.0
  intl_phone_field: ^3.1.0
  open_filex: ^4.3.2
  external_path: ^1.0.3
  path_provider: ^2.0.14
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  permission_handler: ^11.2.1
  device_info: ^2.0.3


dependency_overrides:
  intl: ^0.18.1
  chewie:
    git:
      url: https://github.com/mdeimert/chewie.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  just_audio: ^0.9.30

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - lib/Language/
    - assets/images/PNG/
    - assets/images/SVG/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
